#!/bin/bash
set -e

# Colors to make it nice
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[1;33m'

# Script Dir
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
CLUSTER_NAME="cluster-min"

echo -e "${GREEN} Deploying Minimal K8S Cluster${NC}"

# Checking for required tools
check_dependency() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "{RED}Error: $1 is not installed. Please install it before continuing${NC}"
    exit 1
  fi
}

echo "checking dependencies"
check_dependency k3d
check_dependency kubectl
echo -e "${GREEN}All dependencies installed. Proceeding.${NC}"
echo ""

# Check if cluster exists and prompt  user
if k3d cluster list | grep -q "$CLUSTER_NAME"; then
  echo -e "${RED} Cluster $CLUSTER_NAME already exists.{NC}"
  read -p "Do you want to delete and recreate it? (y/n)" -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Deleting existing cluster..."
    k3d cluster delete "$CLUSTER_NAME"
  else
    echo "Using existing cluster."
  fi
fi

# Create cluster if it dsnt exist (or if we just deleted it)
if ! k3d cluster list | grep -q "$CLUSTER_NAME"; then
  echo -e "{$GREEN}Creating k3d cluster using config file..."
  k3d cluster create --config "$SCRIPT_DIR/k3d-config-min.yaml"
  echo -e "Cluster created successfully!${NC}"
fi

# Configure kubectl to use cluster
echo "Configuring kubectl to use the cluster..."
kubectl config use-context k3d-"$CLUSTER_NAME"


echo -e "\nTo delete the cluster when finished:"
echo -e "${GREEN} k3d cluster delete $CLUSTER_NAME${NC}"
